# NumPy Assigment  

In [ ]:
# 1. Create a 4x4 matrix with diagonal elements as 1 and the rest as 0.

In [1]:
import numpy as np
mat = np.eye(4)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# 2. Generate a 1D array containing the squares of numbers from 1 to 10.

In [2]:
import numpy as np
num = np.arange(1,11)
squ_num = num**2
print(squ_num)

[  1   4   9  16  25  36  49  64  81 100]


In [ ]:
# 3. Calculate the square root of each element in the array [9, 16, 25, 36].

In [3]:
import numpy as np

arr = [9,16,25,36]

sqr_rt = np.sqrt(arr)
print(sqr_rt)

[3. 4. 5. 6.]


In [ ]:
# 4. Create a 2D array with 4 rows and 3 columns, filled with ones.

In [9]:
import numpy as np

arr_2d = np.ones((4,3))
print(arr_2d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# 5. Replace all odd numbers in the array [1, 7, 3, 9, 5] with their squares.

In [12]:
import numpy as np

arr = [1,7,3,9,5]

squ_ar = np.square(arr)

print(squ_ar)

[ 1 49  9 81 25]


In [ ]:
# 6. Calculate the mean of a 2D array with shape (4, 4) filled with random float values.

In [18]:
import numpy as np

arra = np.random.rand(4,4)
print(arra)

mean_val = np.mean(arra)
print("mean of the array is")
print(mean_val)

[[0.89027432 0.52928343 0.92147824 0.89718389]
 [0.72236496 0.22590653 0.33790901 0.91390528]
 [0.60287761 0.42416108 0.76937228 0.61580381]
 [0.30675767 0.01463883 0.81659291 0.54950754]]
mean of the array is
0.5961260864231418


In [ ]:
# 7. Create a 1D array with 10 elements and replace all odd numbers with -1.

In [23]:
import numpy as np

array_d = np.arange(1,11)
print(array_d)

for i in range(10):
  if((array_d[i]) %2 != 0):
    array_d[i] = -1
print(array_d)

[ 1  2  3  4  5  6  7  8  9 10]
[-1  2 -1  4 -1  6 -1  8 -1 10]


In [ ]:
# 8. Extract all elements from a 2D array having random integer with shape (5, 5) except for the outermost border.

In [28]:
import numpy as np

int_arr = np.arange(1,26).reshape((5,5))
print(int_arr)

inner_elem = int_arr[1:-1,1:-1]
print(inner_elem)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [ ]:
# 9. Generate a 4x4 matrix with random integers between 1 to 100 and replace all values greater than the mean with 1, and others with 0.

In [33]:
import numpy as np

rand_matrix = np.random.randint(1,100,size=(4,4))
print(rand_matrix)

mean_value = np.mean(rand_matrix)
print("mean value is :",mean_value)

result = np.where(rand_matrix > mean_value,1,0)
print(result)

[[88 52 25 16]
 [44 13 88 46]
 [83 27 31  7]
 [51  9  5 38]]
mean value is : 38.9375
[[1 1 0 0]
 [1 0 1 1]
 [1 0 0 0]
 [1 0 0 0]]


In [35]:
# 10. Given two matrices:
#    a = np.array([[1, 2], [3, 4]])
#    b = np.array([[5, 6], [7, 8]])
#    Perform matrix multiplication of a and b..

import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

res = np.dot(a,b)
print(res)

[[19 22]
 [43 50]]


In [ ]:
# 11. Create a 3D array with shape (4, 3, 2) and find the sum of each slice along the third dimension.

In [36]:
import numpy as np

array_3d = np.arange(24).reshape((4,3,2))
print(array_3d)

resu = np.sum(array_3d, axis=2)
print(resu)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
[[ 1  5  9]
 [13 17 21]
 [25 29 33]
 [37 41 45]]


In [ ]:
# 12. Create a 3D array with shape (2, 4, 3) having random integers and calculate the mean along the second axis.

In [37]:
import numpy as np

arra_3d = np.arange(24).reshape((4,3,2))
print(array_3d)

resu = np.mean(array_3d, axis=2)
print(resu)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
[[ 0.5  2.5  4.5]
 [ 6.5  8.5 10.5]
 [12.5 14.5 16.5]
 [18.5 20.5 22.5]]
